name: NodeJS Package Publish

on:
  push:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 20.x
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@Heinux-Training'
        
        - name: Install Dependencies
          run: npm install
        
        - name: Build the package
          run: npm run build 

        - name: Publish NPM Package
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npm publish
